### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION (0xc0000005) with 11.0.7+10

### ISSUE THREAD

**Issue by nlmarco** [AdoptOpenJDK/openjdk-build#1713]
I'm unable to re-open the issue https://github.com/AdoptOpenJDK/openjdk-build/issues/1222 and therefore created this here. I assume that otherwise, nobody looks into my new comment, added to a closed bug ;-)

The problem is not solved. It still exists :-( Please look at my comment at the end of https://github.com/AdoptOpenJDK/openjdk-build/issues/1222 for further details.

**Comment by jwachter** [comment]
Hi,

on the Eclipse side the Bug is fixed with 2020-03 (as far as I tested it) (see [Eclipse Bug 558495](https://bugs.eclipse.org/bugs/show_bug.cgi?id=558495)). As they don't provide maintenance releases between the release cycle releases you can either Update or built a custom JDT patch. Company-internal we built a JDT Patch for 2019-12 that worked fine and basically is a one line change.

For the JDK Bug [JDK-8231863](https://bugs.openjdk.java.net/browse/JDK-8231863) it will be fixed as soon as 11.0.8 is released as far as I understand the Backport information there.

Also note that this Bug was not treated by AdoptOpenJDK directly (afaik) as it is not AdoptOpenJDK specific but an upstream bug. That is the original reason why #1222 was closed here as the Report was already present for OpenJDK.

**Comment by aahlenst** [comment]
The issue was closed because it's an OpenJDK problem. The [referenced bug](https://bugs.openjdk.java.net/browse/JDK-8231863) was fixed in 14. The [bug for the backport to 11](https://bugs.openjdk.java.net/browse/JDK-8241685) says it's going to be fixed in 11.0.8, due in July 2020.

I don't see what else we can do here.

**Comment by nlmarco** [comment]
Thanks a lot! I'm going to give the new Eclipse a try (but tomorrow). I agree that you likely can't do anything more, but at least it's now documented here -- maybe helping other's too ;-)

**Comment by nlmarco** [comment]
I just tried the newest Eclipse (build 20200313-1211) and the problem is still the same :-(

**Comment by nlmarco** [comment]
jdk-14.0.1+7 seems to work fine, btw. Just tried it. But don't know, yet, if this causes any other problems.
