### ISSUE TITLE
openjdk9 builds failing on macos

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-build#330]
Ref: https://ci.adoptopenjdk.net/job/openjdk9_build_x86-64_macos/
Builds appear to succeed on [build-macstadium-macos1010-1](https://ci.adoptopenjdk.net/computer/build-macstadium-macos1010-1) and fail on [build-macstadium-macos1010-2](https://ci.adoptopenjdk.net/computer/build-macstadium-macos1010-2).

```

Creating support/modules_libs/java.base/server/libjvm.dylib from 689 file(s)
Creating hotspot/variant-server/libjvm/gtest/libjvm.dylib from 52 file(s)
Creating hotspot/variant-server/libjvm/gtest/gtestLauncher from 1 file(s)
fatal error: malformed or corrupted AST file: 'could not find file '/Users/jenkins/workspace/openjdk_build-refactor/workspace/build/src/hotspot/make/../src/share/vm/gc/shared/plab.hpp' referenced by AST file'
1 error generated.
fatal error: malformed or corrupted AST file: 'could not find file '/Users/jenkins/workspace/openjdk_build-refactor/workspace/build/src/hotspot/make/../src/share/vm/gc/shared/plab.hpp' referenced by AST file'
1 error generated.
make[3]: *** [/Users/jenkins/workspace/openjdk9_build_x86-64_macos/openjdk/build/macosx-x86_64-normal-server-release/hotspot/variant-server/libjvm/gtest/objs/logTestFixture.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: *** [/Users/jenkins/workspace/openjdk9_build_x86-64_macos/openjdk/build/macosx-x86_64-normal-server-release/hotspot/variant-server/libjvm/gtest/objs/test_AltHashing.o] Error 1
fatal error: malformed or corrupted AST file: 'could not find file '/Users/jenkins/workspace/openjdk_build-refactor/workspace/build/src/hotspot/make/../src/share/vm/gc/shared/plab.hpp' referenced by AST file'
1 error generated.
make[3]: *** [/Users/jenkins/workspace/openjdk9_build_x86-64_macos/openjdk/build/macosx-x86_64-normal-server-release/hotspot/variant-server/libjvm/gtest/objs/test_arguments.o] Error 1
fatal error: malformed or corrupted AST file: 'could not find file '/Users/jenkins/workspace/openjdk_build-refactor/workspace/build/src/hotspot/make/../src/share/vm/gc/shared/plab.hpp' referenced by AST file'
1 error generated.
make[3]: *** [/Users/jenkins/workspace/openjdk9_build_x86-64_macos/openjdk/build/macosx-x86_64-normal-server-release/hotspot/variant-server/libjvm/gtest/objs/test_arrayOop.o] Error 1
fatal error: malformed or corrupted AST file: 'could not find file '/Users/jenkins/workspace/openjdk_build-refactor/workspace/build/src/hotspot/make/../src/share/vm/gc/shared/plab.hpp' referenced by AST file'
1 error generated.
make[3]: *** [/Users/jenkins/workspace/openjdk9_build_x86-64_macos/openjdk/build/macosx-x86_64-normal-server-release/hotspot/variant-server/libjvm/gtest/objs/test_bitMap.o] Error 1
fatal error: malformed or corrupted AST file: 'could not find file '/Users/jenkins/workspace/openjdk_build-refactor/workspace/build/src/hotspot/make/../src/share/vm/gc/shared/plab.hpp' referenced by AST file'
1 error generated.
```

**Comment by sxa555** [comment]
Have cleared out the workspace on that machine and will attempt a re-run to see if that's enough to clear the problem

**Comment by sxa555** [comment]
Didn't work ... Manually deleting workspace on the machine and retrying

**Comment by sxa555** [comment]
Confirmed that it is on `-1` - https://ci.adoptopenjdk.net/job/openjdk9_build_x86-64_macos/208 passed

**Comment by sxa555** [comment]
Need to understand what the `openjdk_build-refactor` directory is for and why the builds are referencing it - it doesn't exist on `-2`

**Comment by sxa555** [comment]
Tactical fix implemented until @johnoliver returns from vacation - I have copied the `/Users/jenkins/workspace/openjdk_build-refactor` directory from `build-macstadium-macos1010-1` to `build-macstadium-macos1010-2` so the files it's looking for are present.

**Comment by sxa555** [comment]
Removed important tag as we're now unblocked after the actions in my previous comment

**Comment by karianna** [comment]
This is fixed in the new build scripts, keeping open until we cut over.

**Comment by sxa555** [comment]
This specific problem appears to have disappeared although https://github.com/AdoptOpenJDK/openjdk-build/issues/354 still exists (but is understood to be fixed in the new scripts)
