### ISSUE TITLE
Use of --with-num-cores is not correct, use --with-jobs instead

### ISSUE THREAD

**Issue by neomatrix369** [AdoptOpenJDK/openjdk-build#70]
After a few replies from the OpenJDK builds people on another issue #49, Erik from their side mentions that using `--with-jobs=` instead, see reply:

```
If you want to do the override at configure time, the correct configure
parameter is --with-jobs=4. The --with-num-cores isn't all that useful
except for easier testing of the logic for calculating the default
number of jobs (which is why I left it there).

The default limitation of jobs based on memory is rather conservative (1
job per 1024MB IIRC). We don't like to assume that building is the only
thing the system ever does. Also most of the build tasks aren't that
memory hungry, but some are. I recommend you try manually increasing
jobs until you find your optimal level of concurrency for the types of
builds you do.
…
```
We can easily change this in the `makejdk-any-platform.sh` script for the respective scripts, in our case for the ARM builds.

**Comment by karianna** [comment]
'Fixed' let's see what happens

**Comment by neomatrix369** [comment]
We might still not see the change, if the machine has less than the minimum threshold of memory required for more than one core to be selected. I'll re-run the ARM jobs on our current boxes and see how it goes, we will know when @gdams has the new shiny ARM boxes ready.

**Comment by neomatrix369** [comment]
Just kicked off: https://ci.adoptopenjdk.net/job/openjdk_build_arm_linux/20/console

**Comment by neomatrix369** [comment]
It worked:
```
Build performance summary:
* Cores to use:   4
* Memory limit:   2021 MB
* ccache status:  installed and in use
```
Although is 2 GB good enough, we will see.
